import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full h-[100vh] bg-[#222222] flex justify-center items-center flex-col relative overflow-y-hidden">
          {children}
          <img
            src="/gradient.svg"
            alt=""
            className="absolute bottom-0 z-0"
          />{" "}
        </div>
      </body>
    </html>
  );
}
